### ISSUE TITLE
Mongo version

### ISSUE THREAD

**Issue by vladislavotinov** [jippi/docker-pritunl#16]
Hi! Hello! Could you update the mongo version in your project? Now version - 3.2 .
I need to learn how to backup Mongo Atlas via docker-compose .
Ty

**Comment by vladislavotinov** [comment]
mongodump not work in container.
I updated mongo version and everything is fine

**Comment by nbryant42** [comment]
Looks like mongo was updated to 4.4 along with the switch from xenial to bionic, in a recent commit. But the problem is that migration doesn't happen automatically, so for anyone who built their server based on the earlier docker image and then updated the tag, it fails to start if it finds the 3.x mongodb directory.

**Comment by jippi** [comment]
I've covered upgrade paths and so forth in a new README section, that includes a script that can automate it :) 

https://github.com/jippi/docker-pritunl#upgrading-mongodb
